### ISSUE TITLE
Extend funcionality to other countries

### ISSUE THREAD

**Issue by rafagarcia** [markmarkoh/datamaps#1]
Impressive work. It would be a hit if it could be extended to other countries.

**Comment by ivdekov** [comment]
Hey, how would I get a map centered on Europe?

**Comment by trsonderm** [comment]
@ivdekov change your projection to europe:
```
var projection = d3.geo.equirectangular()
        .center([10, 50])
        .rotate([4.4, 0])
        .scale(1500)
        .translate([element.offsetWidth / 2, element.offsetHeight / 2]);
      var path = d3.geo.path()
        .projection(projection);
```

**Comment by dharmjit** [comment]
Hi All, this is an awesome library and I am using custom map feature of it. I have Senegal Topojson and its not showing in the visual area. I guess I need to set projection correctly, but I am not getting anywhere near to find the values for scale,translate and center. Is there any method to find the values of scale and translate. Thanks

**Comment by FreelanceWebNinja** [comment]
Sorry for the necropost(?), but it appears the additional scopes are not working:

Uncaught TypeError: Cannot read property 'objects' of undefined

**Comment by Anujarya300** [comment]
@markmarkoh 
Really appreciated the work you guys have done. But the datamap only supports for **World** and **USA** map and no other countries. But I need to use **Canada**, **Brazil** maps.

Can you help me how to use the maps of other countries or give me some idea about the map data and rendering, so that I can fix it.

Thanks!

**Comment by Anujarya300** [comment]
By doing some brain storming in the weekend, able to come up with something. I have created demo files for India, Canada etc which shows bubble map. 
https://github.com/Anujarya300/bubble_maps.

Thanks @markmarkoh

**Comment by markmarkoh** [comment]
@Anujarya300 that looks really great. I'd love to have that README available in this project, along with those examples. Feel like sending a pull request?

**Comment by Anujarya300** [comment]
@markmarkoh, Sure, I'd love to put a pull request.

**Comment by mcv** [comment]
I notice all zoom examples use hard-coded coordinates. It would be nice if it was possible to get these coordinates from the continent you're zooming in on. This is possible with countries, but I have no idea if this is also possible with continents. You may have to compare all the bounding boxes of all the countries in that continent, take the min and max of that, and then average the min and max.
