### ISSUE TITLE
Is There a Way to Add the Value as Part of the Labels

### ISSUE THREAD

**Issue by rchaudhuri** [markmarkoh/datamaps#103]
Hello,

I just started looking at Datamaps and was very pleased with the flexibility and convenience.  One question I had is can I easily show the data value as part of the US state label?

For example, if I have the data below, how can I show the "numberOfThings" with the State code without a user having to hover?  I know I can use the map.labels() to show the State codes by themselves, but I also want to show the numberOfThings underneath.

```
    data: {
        NY: {
            fillKey: 'LOW',
            numberOfThings: 2002
        },
        CA: {
            fillKey: 'MEDIUM',
            numberOfThings: 10381
        }
    },
```

Thanks

**Comment by fonziemedia** [comment]
Hi @markmarkoh ,

Your plugin doesn't seem to be working anymore, or I might be missing something on jsbin you've linked..

Just wondering if this should still work or if perhaps, there's another way of doing this.

Cheers!

**Comment by fonziemedia** [comment]
Please disregard my previous comment @markmarkoh I forgot to initiate the plugin with map.labelsWithData() 🤦 
Thanks a lot for this!
