### ISSUE TITLE
Update on resize

### ISSUE THREAD

**Issue by valloq** [markmarkoh/datamaps#12]
Any plans to allow the map to redraw automatically when the browser is resized?

**Comment by maeishoj** [comment]
@gabrielfagundez  how do I get your "responsivness" changes in my source? sorry bit of a noob here :/

**Comment by maeishoj** [comment]
On line 67 of datamaps: d3.select(this.options.element).style({'position': 'relative', 'padding-bottom': '60%'});  if I comment that out (or if i remove padding-bottom) solves my issue. Not sure why padding bottom is needed nor why it causes my map to shrink to 3px x 2px :/

**Comment by maeishoj** [comment]
@justmarkup I have a problem with the resize.

I am highlighting continents on hover. then when clicking on a continent i'm zooming into it's most-centered country. and everything works fine.
When I do so, I have to open a sidebar from the left, which resized my main div where the map is to 66% (from 100% it was initially) (resize is not called automatically when this happens).
So I thought to call map.resize() after I have my new width and height for my div (that contains the map).

This also works fine. However the map is now resized and not zoomed in any longer in my wished area. Even though the zoom in code is the same and I call that right after map.resize() this doesn't work anylonger... you can see it here: bacp-staging.azurewebsites.net

I would appreciate it anyone could help me out :/

**Comment by justmarkup** [comment]
@maeishoj 

Hi, could you please provide a reduced test case, it's hard to debug your site as their is a lot of other logic involved and the sidebar currently goes crazy here in my Chrome/Firefox. You can also contact me via hallo@justmarkup and I am happy to help.

**Comment by maeishoj** [comment]
@justmarkup  Hey there. Thanks for your assistance. I wrote you a mail. 

However as I mentioned what happens is basically that as soon as i add:
`window.addEventListener('resize', function(event) {
            map.resize();
        });`

and I resize the map, the the zoom doesn't work anylonger, which I am not sure why. 

My zooming is implemented as described here: (http://bl.ocks.org/mbostock/2206590) .
Anyone has any idea of why this may be?

**Comment by justmarkup** [comment]
The problem was that you were zooming by setting transform via an attribute, if you use style instead everything works, see example: justmarkup.com/tests/datamap-zoom.html

**Comment by Artenuvielle** [comment]
The resize works like a charm but  the borderwidth of the countries are not updated. If I initialize the map at a very big scale the borderwidth is something like 5px (haven't checked the exact value). Upon downscaling the map this does not change which causes a map with a width of 100px to be pretty much all black.

**Comment by justmarkup** [comment]
Hi @Artenuvielle 

you are right, the borderwidth gets calculated wrong. I just pushed a potential fix for this in my repo: https://github.com/justmarkup/datamaps/commit/62388898fdf1608e407451e4f121eec86078d6f1 Can you please check if this also solves your issue.

For testing you could add this line of JavaScript to your site:
```
d3.select('.datamap').select('g').selectAll('path').style('vector-effect', 'non-scaling-stroke');
```

**Comment by adrianbj** [comment]
Not directly related to this issue, but like @Artenuvielle I had issues with the padding-bottom:60%. I changed it to 40% and everything looks great. Otherwise there was way too much padding, both top and bottom. The custom map in question very landscape in it's dimensions: https://gist.github.com/adrianbj/ea7b8c60dea3bfb0a2a1

Seems like the padding-bottom approach is never going to work properly in all situations.

**Comment by justmarkup** [comment]
Well, padding-bottom: 60% (more accurately 56.25%) only works for maps with a ratio of 16:9 

But as this is added via CSS anyway I don't see a problem here. You can always change that value of your map is not 16:9

**Comment by adrianbj** [comment]
@justmarkup - of course, and I did override the css to suit my map's dimensions, but I guess I was thinking there might be a more universal approach to using padding-bottom? If not, I think it would be useful to mention it in the docs in the responsive section.

**Comment by adrianbj** [comment]
Actually thinking through this a little more - the site I am working on is going to have many different maps, all with very different aspect ratios. The one codebase will need to control all these maps, so the padding-bottom will need to be added dynamically based on the dimensions of the map, so I am going to need to grab these dynamically and set then automatically set the padding-bottom based on the aspect ratio. Shouldn't be too difficult, but I am wondering if that calculation could be made in the core of datamaps instead of hard-coding the value?

**Comment by justmarkup** [comment]
@adrianbj Yes you are right, we should change this and add it to the core. I think I found a solution, can you please add this:

```
d3.select(this.options.element).style({'padding-bottom': ((parseInt(d3.select(this.options.element).select('svg').style('height')) / parseInt(d3.select(this.options.element).select('svg').style('width'))) * 100) + '%'});
```
after this line

```
d3.select(this.options.element).select('svg').style({'position': 'absolute', 'width': '100%', 'height': '100%'});
```

and check if this solves the issue for you?

**Comment by adrianbj** [comment]
Thanks for looking into this, but unfortunately that doesn't work. The values returned for width and height are completely affected by the initial padding-bottom value. I am actually at a bit of a loss on how to get dimensions of the svg.

I just played around with adding a new aspectRation option that you can define in the map setup. So if you define it as 0.3, then I use that like this:

```
d3.select(this.options.element).style({'position': 'relative', 'padding-bottom': (aspectRatio*100) + '%'});
```

Not sure if you guys think this might be a reasonable approach to the problem. Obviously it would be better if it could be automatically calculated.

Obviously my changes to support this are very simple, but let me know if you'd like a PR.

**Comment by justmarkup** [comment]
Just tried other methods to get the correct height of the svg, but also without luck. 

I like your solution @adrianbj , would be great if you could do a PR. As the default value, we should use 0.5625 (16:9) so sites relying on the current implementation won't break.

**Comment by adrianbj** [comment]
Done!

https://github.com/markmarkoh/datamaps/pull/198

**Comment by Downchuck** [comment]
@adrianbj Looks like this issue could be closed. That said: using the custom USA map without height being set on the container seems to be buggy. The map has about 30% whitespace padding above it in those cases.. (container.style.width = '100%', no height set).

**Comment by johhorn** [comment]
@justmarkup I also have issues with zoom on responsive maps, but changing the .attr to .style as suggested previously (justmarkup.com/tests/datamap-zoom.html) does not seem to help. Any suggestions on how to make it work?

The example I have based my zoom on: http://jsbin.com/boribamugo/1/edit?html,output

**Comment by dvolz** [comment]
Does anyone know if this is supposed to work in Internet Explorer? I am not finding it working at all in IE 9-11.

**Comment by andela-oifedapo** [comment]
@dvolz a fix for this was merged recently https://github.com/markmarkoh/datamaps/pull/235 but I don't think it got released yet
