### ISSUE TITLE
updateChoropleth bug when subunit names don't make valid selectors

### ISSUE THREAD

**Issue by ramnathv** [markmarkoh/datamaps#127]
Not sure if this is fixable in `datamaps`, but thought I should bring it up anyways. One of the users of `rMaps` noticed that weird things happen when subunit names have certain characteristics. For example, consider `nord - pas-de-calais`. When `updateChoropleth` was called with this as one of the subunit names, it errored out, and moreover did not complete the updates for all records that occured after this one.

More investigation revealed that the trouble is that `d3.select('.' + subunit)` errors out, since it does not see a valid query selector. So my questions is, can `updateChoropleth` and `datamaps` sanitize subunit names in a way that will lead to more robust behavior, or is this better left to the user.

Note that several times the limitation is not the CSV file, but the geoJSON file one can get their hands on. So user updates have to happen in both, which is why I thought it would be easier to handle in `datamaps` itself.

**Comment by WunderBart** [comment]
What about countries that have `id: -99`?

**Comment by WunderBart** [comment]
What about countries without ISO ID (the `-99` issue)? World topojson contains actually 3 of them which leads to 3 identical IDs for the `svg` collection. I can modify source manually but it would be nice to have some fallback in `updateChoropleth` in such situation.
