### ISSUE TITLE
Hovering over District of Columbia

### ISSUE THREAD

**Issue by mg1075** [markmarkoh/datamaps#133]
I am not able to get any hover indication when hovering over the District of Columbia.
For example, try hovering over the election map on the datamaps site: 
http://datamaps.github.io/

Is this just standard behavior, because DC is so small?

Should the State abbreviation labels also be able to trigger 
a popup, so one can determine any values associated with DC?

**Comment by markmarkoh** [comment]
I believe #169 is addressing the state abbreviation hover.

Since DC is so small, it would be nearly impossible to offer a hit state big enough unless the map is zoomed in.
