### ISSUE TITLE
Is there a way to target the continents EUROPE and AFRICA rather than by individual countries?

### ISSUE THREAD

**Issue by mhj212** [markmarkoh/datamaps#138]
Is there a way to target the continents EUROPE and AFRICA rather than by individual countries?

**Comment by matzke** [comment]
+1

**Comment by Tuhaj** [comment]
I think it would be a useful feature to add something like
`scope: 'continents'`
Has anybody implemented it already?

**Comment by walterspieler** [comment]
+1
Would be a great feature.

**Comment by nike121** [comment]
+1 would really love this
