### ISSUE TITLE
Is there a way in the Choropleth Map to reset all countries to defaultFill value?

### ISSUE THREAD

**Issue by mrweix** [markmarkoh/datamaps#141]
In the updateChoropleth() funtion I am looking for a way to reset ALL the countries to the defaultFill value. The background is that I am animating a choropleth map over years (similar to http://rmaps.github.io/blog/posts/animated-choropleths/), but I have different data for different years....

Lets say in my initial year I have data for Mexico. The Choropleth Map gives Mexico a Color. if I change to a year where I don't have data from Mexico, all countries get updated except Mexico, because there is no data to update it.... 

Any ideas how I can do this with datamaps, except create an empty data point for Mexico?

**Comment by Adhara3** [comment]
Hi, this would be very useful. Especially to easy animation. Maybe a second parameter on the update call to reset the previous one?

Nice work indeed!
Andrea

**Comment by BernhardSmuts** [comment]
May try this:

`map.updateChoropleth(null, {reset: true})`
