### ISSUE TITLE
Problem with onClick and onLeave events on a country

### ISSUE THREAD

**Issue by giorgio-zamparelli** [markmarkoh/datamaps#145]
I found a strange behaviour happening after selecting a country by a click and leaving it.

I'm trying to create a map very similar to the sample one called Multi-select
http://files.stevenskelton.ca/d3-geomap/examples/multiselect.html
This problem is happening in both the datamaps library and the Polymer wrapper d3-geomap.

Here is how to reproduce it:
1) Click on any country and release, the mouse cursor must remain within the borders of the country.
2) The country is now selected and orange and the mouse cursor is still inside
3) Move out of the country the mouse cursor, this will cause the country color to go back to green while it should stay orange.

Any idea on how to solve this?
![screenshot 1](https://cloud.githubusercontent.com/assets/1902092/4908722/cc90c97c-646c-11e4-91cb-ca06175e78af.jpg)
![screenshot 2](https://cloud.githubusercontent.com/assets/1902092/4908723/ccb6f5a2-646c-11e4-8b58-6c82458a6ca0.jpg)

**Comment by mruaim** [comment]
what is the solution?
