### ISSUE TITLE
Mouse Wheel Zoom Map

### ISSUE THREAD

**Issue by Hixon10** [markmarkoh/datamaps#146]
Hi.
I saw example of static zoom. But I wish a Mouse Wheel Zoom Map. Is there some way to implement this feature?

**Comment by markmarkoh** [comment]
http://jsbin.com/boribamugo/1/edit?html,output

**Comment by krehl** [comment]
Hi, is it possible to change the line thickness while zooming in?

**Comment by krehl** [comment]
Hi, is it possible to change the line thickness while zooming in?

**Comment by juliohm** [comment]
This example should be well documented in the readme, it is awesome and simple!

**Comment by MahaveerReddy** [comment]
hi 
  i need to create a map with zoom in zoom out with negative zoom out upto an (-100) .. how come i can implement that

**Comment by BernhardSmuts** [comment]
> Hi, is it possible to change the line thickness while zooming in?

This little piece worked perfectly for me:

datamap.svg.selectAll(".datamaps-arc").style("stroke-width", (1/d3.event.scale)*2+"px");
