### ISSUE TITLE
Add map legend support

### ISSUE THREAD

**Issue by markmarkoh** [markmarkoh/datamaps#15]
Add a plugin to render a simple map legend based on your fill data.

**Comment by ugokoli** [comment]
I am totally lost. I can't find anywhere on how to implement the datamaps legend to work for me. I don't even know where to locate and download the datamaps legend plugin files. @markmarkoh I need your help. Thank you.

**Comment by mcsmithers** [comment]
I might need a little help myself.  I have a global map and am trying to use the legend.  The map itself looks great, but the legend has the color categories and then many more.
![screen shot 2018-05-09 at 1 59 34 pm](https://user-images.githubusercontent.com/5580479/39839559-54c87eea-5391-11e8-9c7a-c8392d3dc0f6.png)

I don't think I have any ideas that stand out as to why this might be, but maybe is there a way to tell the legend to only include the specified colors for the highs, mediums, lows, etc?

```
 var fills = {
            defaultFill: '#d9f0a3',
            UNKNOWN: '#addd8e',
            LOW: '#78c679',
            MEDIUM: '#31a354',
            HIGH: '#006837'
        }

        function intToColor(integer) {
            const key = "color" + _.toString(integer)
            fills[key] = colors(integer)
            return key
        }

 function convertDataToDatamapData(jsonData) {
            var h = {}
            _.each(jsonData, function(el) {
                const revenue = _.toInteger(el["Stat"]["revenue"])
                const countryCode = cleanCountryCode(el["Stat"]["country_code"])
                    // console.log(countryCode + " has " + revenue + " revenue");
                h[countryCode] = {
                    fillKey: intToColor(revenue)
                }
            })
            return h
        }
        var data = convertDataToDatamapData(jsonData)

        var basic_choropleth = new Datamap({
            element: document.getElementById("container"),
            projection: 'equirectangular',
            fills: fills,
            geographyConfig: {
                borderColor: '#000000'
            },
            data: data
        });
```
