### ISSUE TITLE
Somaliland have negative ID

### ISSUE THREAD

**Issue by ranska** [markmarkoh/datamaps#151]
Usecase: 
Given i make a map scoped on Africa
And i do some click event like """
```Javascript
 done: function(datamap) {
        datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography) {
            // change color using geography.id
        });
    }
```
"""
Then i give the following message error """
   Uncaught SyntaxError: An invalid or illegal string was specified.
"""

the id is the only negative number that i found
```Javascript
geometry: Object
id: "-99"
properties: Object
```
is it normal ?

**Comment by maeishoj** [comment]
All regions that are disputed in every map i encountered (this, jQvmap etc) give a negative value to them. Not sure why, but you can modify the source yourself if you need to have it..
