### ISSUE TITLE
Get tooltip to show while having custom mouseover event.

### ISSUE THREAD

**Issue by maeishoj** [markmarkoh/datamaps#154]
Hey everyone,

first off, awesome job!

I was wondering if it's possible to manually invoke the tooltip when a "mouseover" event is called, because if I use something like this:

`datamap.svg.selectAll('.datamaps-subunit').on('mouseover', function(geography) {
                    $scope.tooltipInUse = $scope.currentContinent;
                    highlightRegionOfCountry(geography.id.toLowerCase());
                });`

Then the tooltip gets disabled.

While I would still like to have it showing.

**Comment by kieraneglin** [comment]
Were you able to fix this issue?  If so, how?

**Comment by kieraneglin** [comment]
For anyone in the future, if you use 'mouseenter' and 'mouseleave' instead, the tooltip shows up.
