### ISSUE TITLE
Problems with popup on hover while zoom

### ISSUE THREAD

**Issue by illyashevchenko** [markmarkoh/datamaps#155]
There is some issue "with popup on hover" while using zooming (https://github.com/mbostock/d3/wiki/Zoom-Behavior)

Popup positioninig is not working properly.
I believe that is because of coordinates changes (svg is scaled and translated)

I changed popup calculations in "Datamap.prototype.updatePopup" method from using 
"d3.mouse(this)" to using "d3.event.offsetY" and "d3.event.offsetX". It helps quite well.

Is there any other way to fix thid and if not - it might be usefull to use real mouse coordinates to show popup.

**Comment by arthyn** [comment]
I had this same issue. Was using the US map, but the g element of the svg wasn't filling the whole space so I scaled and translated it. However this caused the popup to go under the mouse pointer which was causing problems highlighting and clicking states. I used the above fix and that solved the problem.
