### ISSUE TITLE
Change links in Readme to https

### ISSUE THREAD

**Issue by justmarkup** [markmarkoh/datamaps#156]
The scripts hosted on d3js.org are not reachable via https, so better link to //cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js (so there are reachable via http and https), as suggested on the d3js.org site.

@markmarkoh Do you see any disadvantages in doing this? If not, I will prepare a PR

**Comment by markmarkoh** [comment]
That sounds fine!
