### ISSUE TITLE
Why won't data:data work?

### ISSUE THREAD

**Issue by abrice** [markmarkoh/datamaps#163]
HI,

If I define data = {'USA': { fillKey: "#ff9900" }} and then in new Datamap... have data: data, nothing happens. Do I have to hand-code so that it is data: {'USA': { fillKey: "#ff9900" }}?

Basically I want to dynamically create a data object and provide that to Datamap. But it doesn't like that... Or am I just missing something obvious?

Thanks,
Andrew

**Comment by markmarkoh** [comment]
@abrice It doesn't need to be hardcoded, I think there may be a typo elsewhere in your code?

Here is an example of what you are describing: http://jsbin.com/duqitafuzo/1/edit?html,output
