### ISSUE TITLE
bubblesConfig behavior does not match documentation

### ISSUE THREAD

**Issue by zyphlar** [markmarkoh/datamaps#175]
It appears there are two ways of configuring bubbles, but only one of those ways works.

From [the website](https://github.com/datamaps/datamaps.github.com/blob/master/index.html#L675) and [the source code](https://github.com/markmarkoh/datamaps/blob/master/src/js/datamaps.js#L34): 

```
    bubblesConfig: {
        borderWidth: 2,
        borderColor: '#FFFFFF',
        popupOnHover: true,
        popupTemplate: function(geography, data) {
          return '<div class="hoverinfo"><strong>' + data.name + '</strong></div>';
        },
        fillOpacity: 0.75,
        animate: true,
        highlightOnHover: true,
        highlightFillColor: '#FC8D59',
        highlightBorderColor: 'rgba(250, 15, 160, 0.2)',
        highlightBorderWidth: 2,
        highlightFillOpacity: 0.85,
        exitDelay: 100
    },
```

From README.md and Issue #135 which was dismissed without fix:
```
//draw bubbles for bombs
bombMap.bubbles(bombs, {
    popupTemplate: function (geo, data) { 
            return ['<div class="hoverinfo">' +  data.name,
            '<br/>Payload: ' +  data.yeild + ' kilotons',
            '<br/>Country: ' +  data.country + '',
            '<br/>Date: ' +  data.date + '',
            '</div>'].join('');
    }
});
```

Despite what the website and source code appear to indicate, the only way to pass bubblesConfig options is via the `Datamap.bubbles()` function as a second parameter, instead of in the `new Datamap(options)` constructor as I would expect. So I'm actually running `my_map.bubbles(bubbles,my_map.options.bubblesConfig);` which seems like the sort of thing that ought to be fixed in the library.

**Comment by markmarkoh** [comment]
Thanks for the bug report @zyphlar 

I updated the library to address this issue. When you get a chance, see if version `0.3.7` works as expected.

If not, please reopen.
