### ISSUE TITLE
Is there a way to make labels as link

### ISSUE THREAD

**Issue by manthan1985** [markmarkoh/datamaps#180]
Is there a way to make labels as link?

states like: NK, CT, DE, MD, DC... (states which have state abbreviation out site of the map) 

It is really hard to click on DC. So, Is there a way to make labels as link?

**Comment by twodayslate** [comment]
http://bl.ocks.org/ramnathv/8936426

If you want to make an element act like a link on click do `.on('click', function(d) { window.location.href = "http://google.com"; });
