### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by wadjo** [markmarkoh/datamaps#181]
Hi,
Thank you for releasing DataMaps ! I appreciate your efforts. But please can we provide an image instead of the bubbles ?
Hope there is a solution ...

Thanks !

**Comment by markmarkoh** [comment]
@wadjo I whipped up a custom plugin for your to mess around with, here is the working example:

http://jsbin.com/pamigahifi/1/edit?html,output

Notes:
1. Custom URLs can be passed in for each marker
2. You can set a default
3. Markers are hard coded to 20x20px, this can be easily changed by updated the `handleMarkers` function

You can play around with `handleMarkers` as much as you feel necessary to get this plugin to your likings.

Last note:
**This is not part of DataMaps core - this is just using DataMap's plugin system**

![screen shot 2015-04-19 at 3 12 31 pm](https://cloud.githubusercontent.com/assets/11268/7221173/99de657c-e6a6-11e4-82f1-471bacab28a5.png)
