### ISSUE TITLE
Adding multiple projections with different latitudes/longitudes 

### ISSUE THREAD

**Issue by eoktay** [markmarkoh/datamaps#184]
Hi, I had looked at a potential way generating multiple projections from a country to a country by looking at the 'Projections & Graticules' example on http://datamaps.github.io/.

So, I added more points to `map.arc`; however, the start of the projections all go to the US[the target points also randomly go to places]. 

Is there a limit as to how many coordinates `map.arc` can handle? Just asking this to see if Google's Geocoding is used behind the scenes, which sets a limit for non-licensed users.

Thanks!
Erden

**Comment by markmarkoh** [comment]
@eoktay Datamaps doesn't use Google's Geocoding, so there isn't any license issue. Can you post a link to your issue?

Good starting point: http://jsbin.com/yirehojeni/1/edit
