### ISSUE TITLE
Split Bubble Color

### ISSUE THREAD

**Issue by merlinpatt** [markmarkoh/datamaps#185]
Is there a way for me to fill in a bubble with more than one color?
I'd like to create pie charts on the map.

**Comment by markmarkoh** [comment]
@merlinpatt The current bubble system is a plugin, and while it doesn't support pie-charts, you could write your own plugin:

http://datamaps.markmarkoh.com/creating-a-datamaps-plugin/

[Starting from the current bubbles plugin](https://github.com/markmarkoh/datamaps/blob/master/src/js/datamaps.js#L426) would probably be most beneficial.
