### ISSUE TITLE
Displaying multiple scopes

### ISSUE THREAD

**Issue by ninjatronic** [markmarkoh/datamaps#187]
Is it possible to render more than one scope at a time? I have a topoJSON file with two objects in and I'd love to be able to display them both at the same time.

**Comment by markmarkoh** [comment]
@ninjatronic Sure, you just have to call `new Datamap` again with the new projection.

Working example:
http://jsbin.com/jeloyiwuxa/1/edit?html,output

**Comment by ninjatronic** [comment]
Hi @markmarkoh 

Maybe I didn't explain myself correctly. My topoJSON file has a set of objects for England (objects.england) and one for Scotland (objects.scotland). If I set the scope to "england" it displays England and if I set the scope to "scotland" it displays Scotland. I'd like to find a way to set the scope to show both sets of objects at once ("[england,scotland]" or similar).

is that a bit clearer?

Thanks

**Comment by timaschew** [comment]
> Working example:
http://jsbin.com/jeloyiwuxa/1/edit?html,output

the link is dead

**Comment by markmarkoh** [comment]
@timaschew It's still working for me (in incognito mode as well)

**Comment by timaschew** [comment]
this is very strange:

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/1t341t462S3x2o3x450D/Image%202015-07-07%20at%2010.04.56%20nachm..png)

**Comment by justmarkup** [comment]
@timaschew Also works for me in Chrome and Firefox (logged in and as anonymous user). Which browser are you using? I remember having a similar problem with another jsbin where I wasn't able to see the code in some cases.

I made a clone -> http://jsbin.com/yezaqi/1/edit?html,css,js,console does this work for you?

**Comment by timaschew** [comment]
yes, it's working, but the other link is working now as well :flushed:

**Comment by justmarkup** [comment]
Ok, great :-)

**Comment by adrianbj** [comment]
I am not sure that the example actually answers the OP's question. At least it doesn't match my need, which I think is the same as his. I am trying to display one single topojson file that has three component objects: https://gist.github.com/adrianbj/c7b4e145e9384b446ab8

I want the map to look like it does on github - ie display all three objects together. As you'll see, the objects are of different types: Multipolygon, Polygon, Linestring, so it's not possible to combine them into one object (at least as far as I know it isn't). Any ideas how I might make this work?

Thanks!
