### ISSUE TITLE
onhover popup display offset bug

### ISSUE THREAD

**Issue by pbella** [markmarkoh/datamaps#190]
There seems to be an issue with position used to display the onhover popups.  Specifically, I have noticed that if a datamap appears after a list, any onhover popups will be offset from the map element they are annotating.  Here's an example of the expected behavior (hover over one of the red shaded countries to see the popup):
http://randomsamples.info/test/dmhover-works

here is the same map with a list displayed above it on the page (notice the position of the onhover popups relative to where they were on the first link)
http://randomsamples.info/test/dmhover-offset

This behavior occurs in both Firefox and Chrome.

**Comment by twodayslate** [comment]
Is the `position: relative;`?

**Comment by pbella** [comment]
No, it's position: absolute;

**Comment by cghil** [comment]
I noticed a similar bug. Tooltip seems to be popping up in a strange place.
![screen shot 2015-06-19 at 5 23 13 pm](https://cloud.githubusercontent.com/assets/7528130/8265181/577b8a7a-16a8-11e5-8eba-118017031f0f.png)

**Comment by diogocp** [comment]
You need `position: relative;` according to #119.
