### ISSUE TITLE
fill on click?

### ISSUE THREAD

**Issue by aljamala** [markmarkoh/datamaps#191]
Is there a way to fill a region (state in my example) when clicked? I basically want the user to be able to select/deselect states by clicking on the map, hence creating their own region.

**Comment by aljamala** [comment]
If I submit a Pull Request to handle click events and fill on click would you accept it?  I already have made the changes locally and they seem to be working out pretty well so far.

**Comment by markmarkoh** [comment]
@aljamala It doesn't sound like it'd be useable by a mass audience. Typically the features I add (or PR's I end up accepting) are geared towards Data Visualization.

I think this use-case is cool and I'd love to see it, but I'm not sure if it'd make sense to have as a core part of the library.

**Comment by davorb** [comment]
@aljamala I don't suppose you could write it as a plugin, or at least put it on gist since I'm working on something similar right now.

**Comment by markmarkoh** [comment]
@davorb that's actually a great point.

If most of the logic could be [encapsulated as a plugin](http://datamaps.markmarkoh.com/creating-a-datamaps-plugin/) this could be useful.

If there was a [generic utility function](https://github.com/markmarkoh/datamaps/blob/master/src/js/datamaps.js#L661) added to the source, I'd be open to accept that in a PR if it helped out the plugin (and future plugins, hopefully).

cc @aljamala

**Comment by markmarkoh** [comment]
Feel free to reopen if someone has a plugin they'd like to contribute to the core! Closing for now.
