### ISSUE TITLE
Putting text into a bubble

### ISSUE THREAD

**Issue by 29er** [markmarkoh/datamaps#196]
I'm sure this is something that I am overlooking, but I just want put a number inside a bubble, without having to hover. is there a property i can use ??
IE: 
 var bombs = [{
        name: 'Joe 4',
        radius: 25,
        yield: 400,
        country: 'USSR',
        fillKey: 'RUS',
        textInBubble : '2344',   // no hover just show it
        significance: 'First fusion weapon test by the USSR (not "staged")',
        date: '1953-08-12',
        latitude: 50.07,
        longitude: 78.43
      }

Thanks!

**Comment by KurganskySergey** [comment]
same question! thanks in advance.
