### ISSUE TITLE
Custom texture to the map?

### ISSUE THREAD

**Issue by ackzell** [markmarkoh/datamaps#199]
Hi, 

Is there any way to add a png overlay or even better to fill the map with a texture of some kind?

I would appreciate if pointed to the right direction.

**Comment by ackzell** [comment]
So, I think this is actually what I'm looking for:

http://datamaps.markmarkoh.com/custom-fill-patterns-for-datamaps/

**Comment by markmarkoh** [comment]
Great! Glad that post helps.

**Comment by mikebotazzo** [comment]
The current link no longer exists. Here is the [file](http://jsbin.com/aYAQiver/3/edit?html,output) that was used in the example.
