### ISSUE TITLE
Not getting click event on Tablet

### ISSUE THREAD

**Issue by harjitdotsingh** [markmarkoh/datamaps#207]
Hi there,

I have the following piece of code 

map = new Datamap({
            scope: 'usa',
            responsive: true,
            geographyConfig: {
                highlightOnHover: false,
                borderColor: 'orange'
            },
            element: document.getElementById('map'),
            done: function (datamap) {

                FPOC.INIT.handleMapClick(datamap)

            }

        })

I don't get any clicks when touching a map area on a tablet ? Any clues why ?

**Comment by justmarkup** [comment]
@harjitdotsingh What does the function ``` FPOC.INIT.handleMapClick(datamap) ``` do?

Just tested with

```
done: function(datamap) {
    datamap.svg.selectAll('.datamaps-subunit').on('click', function(geography) {
        alert(geography.properties.name);
    });
},
```

on an iPad and an Android Device (Nexus 7) and it worked as expected.
