### ISSUE TITLE
Russia is on both side of the map

### ISSUE THREAD

**Issue by Merdok** [markmarkoh/datamaps#208]
![image](https://cloud.githubusercontent.com/assets/13096847/8402157/26860eb8-1e41-11e5-8d3b-0c128ceb14ec.png)

Hi, as you can see in my attached photo, Russia in on both sides of the map.
Sorry if this is a noob question...

Just started to learn :D

Thanks,

Merdok

**Comment by Downchuck** [comment]
That's a fairly typical representation.

**Comment by justmarkup** [comment]
As @Downchuck said this is a common pattern. 

You can change the center position of the map if you like, eg to start with Alaska, not Russia on the very left you can use:

```
var map = new Datamap({
    element: document.getElementById('container'),
    setProjection: function(element) {
        var projection = d3.geo.equirectangular().center([14, 0]);
        var path = d3.geo.path().projection(projection);
    
        return {path: path, projection: projection};
    }
});
```

Hope this helps.

**Comment by markmarkoh** [comment]
Closing since @justmarkup provided a workaround

**Comment by abhickbiswas** [comment]
I hope this will be of some help for people coming around with this issue. The solution will be 
`var width = document.getElementById('map').offsetWidth;
    var height = width;
    // render map
    var map = new Datamap({
        element: document.getElementById('map'),
        //projection: "mercator",
                setProjection: function(element) {
                    var projection = d3.geo.mercator().translate([(width/2), (height/2)]).scale( width / 2 / Math.PI).rotate([-11,0]);
                            //d3.geo.mercator().center([10,60]).scale(100);
                    var path = d3.geo.path().projection(projection);
                    return {path: path, projection: projection};
                }
    });`
<img width="611" alt="screen shot 2017-03-23 at 1 15 11 am" src="https://cloud.githubusercontent.com/assets/24697106/24217550/3f17262a-0f66-11e7-9ca6-6d6651faf005.png">
