### ISSUE TITLE
Bubbles Issue

### ISSUE THREAD

**Issue by ishort** [markmarkoh/datamaps#21]
Hi,

I've been following the examples on the main page, and can get them all working.  However, if I modify the bubbles map to use: dataUrl: '/data/uk.topo.json' (and create some bubbles over the UK), the bubbles appear beneath the map.  Is there any reason for this, and is there any way and can get them to appear above the map?

Thanks,

Ian

**Comment by ValterSantosMatos** [comment]
Hi there @markmarkoh, I was hitting the same async problem and got the answer in this thread. If you recon this should be the correct way to create the bubbles I can create a PR to change the documentation.

From:
```
var bombMap = new Datamap({  });
var bombs = [{}]

//draw bubbles for bombs
bombMap.bubbles(bombs, {})
```

To
```
var bombs = [{}]

var bombMap = new Datamap({
   //all your options
   done: function( datamap ) {
      datamap.bubbles([{...}], bombs)
   }
 });
```

Cheers
