### ISSUE TITLE
Zoom demo is broken on website.

### ISSUE THREAD

**Issue by aeschylus** [markmarkoh/datamaps#213]
The Zoom example using `setProjection()` is broken in Chrome. The error reads: 

"Uncaught TypeError: a.target.className.indexOf is not a function"

**Comment by markmarkoh** [comment]
@aeschylus What chrome version are you using? OS?

**Comment by aeschylus** [comment]
Version 44.0.2403.125 (64-bit)
MacOS 10.9.5

**Comment by markmarkoh** [comment]
Can't repro this issue, closing for now.
