### ISSUE TITLE
BUG: oscillate mouse between countries, countries stay selected

### ISSUE THREAD

**Issue by jchamet** [markmarkoh/datamaps#214]
On mouse enter, selection changes color and on mouse leave, selection returns to default. This is expected behavior.

However, if you quickly move the mouse to another selection, the previous selection does not fully return to default color and remains partially selected and highlighted. See below for result. Note that my cursor was not within the svg element when I took the screenshot.

![screenshot from 2015-08-04 14 14 14](https://cloud.githubusercontent.com/assets/5588669/9068735/2f3500da-3ab3-11e5-8436-a10fee664267.png)

**Comment by workgena** [comment]
I can't reproduce this behavior(Firefox 41). Can you, please, give the example on jsfiddle.net and specify the browser?
