### ISSUE TITLE
Spawning new arcs

### ISSUE THREAD

**Issue by raynerd** [markmarkoh/datamaps#222]
Hi, I want to spawn new arcs on a map at random times. the fact is that when I call the map.arc function with the new arc as parameter all the other arcs are removed or hide. There is a way to create new arcs on top of the older and removing them after a custom timeout?

**Comment by markmarkoh** [comment]
@raynerd There is a way, it just involves always calling `map.arc`with the full set of arcs.

For example, if you had 3 arcs originally:

```javascript
var arcs = [arc1, arc2, arc3];
map.arc(arcs);

// Make an ajax call for 2 more arcs
d3.JSON('/arcs', (newArcs) => {
  // this is what you are seeing, the original 3 are removed
  map.arcs(newArcs)

 // instead of the above, concat `newArcs` to `arcs`
 arcs = arcs.concat(newArcs)
 map.arcs(arcs)

 // all arcs should be present now
})
```

Can you give that a shot?

**Comment by raynerd** [comment]
I forgot to say thanks

**Comment by markmarkoh** [comment]
No problem @raynerd!
