### ISSUE TITLE
Bubbles Image background

### ISSUE THREAD

**Issue by AmadeiMatt** [markmarkoh/datamaps#224]
Hi Mark! I'm trying to use your project. I have some problems with your bubbles. I need to put an image as background of the bubble. it's possible to do it? 
Thank you very much,
See you soon and have a nice day,
Matteo Amadei

**Comment by markmarkoh** [comment]
Hey @AmadeiMatt 

#223 was just merged which allows for filters as bubble backgrounds. I think it's possible to use an image as a filter in SVG. You'll have to build from master to get that new functionality.
