### ISSUE TITLE
Using latitude and longitude to center maps

### ISSUE THREAD

**Issue by arshad** [markmarkoh/datamaps#226]
I have a datamap using the following code:

```
var map = new Datamap({
        scope: 'world',
        element: document.getElementById(mapID),
        data: mapData,
        setProjection: function(element) {
          var projection = d3.geo.mercator()
            .center([lat, long])
            .scale(130)
            .translate([element.offsetWidth / 2, element.offsetHeight / 2]);
          var path = d3.geo.path()
            .projection(projection);

          return {path: path, projection: projection};
        },
        geographyConfig: {
          popupOnHover: false,
          highlightOnHover: false
        }
      });
```

I'm centering the map dynamically using `lat` and `long` for the projection center. This works fine for US and European countries.

But for Eastern countries (Japan and China), it only works if I swap the latitude and longitude. See below:

```
          var projection = d3.geo.mercator()
            .center([long, lat])
            .scale(130)
```

Anything I'm missing here?

**Comment by markmarkoh** [comment]
What values for lat and long are coming in? Are you sure you are setting the values to be negative/positive based on where you are trying to center?

Can you edit this JSbin with non-working examples?

http://jsbin.com/jowodivonu/edit?html,output

**Comment by arshad** [comment]
Yep. See http://jsbin.com/lokuhuqami/1/edit?html,output

I've got two centers: `center` and `rcenter`. It works with `rcenter` but not with `center`.

**Comment by markmarkoh** [comment]
Is this what you are trying to do? Note the negative GPS coords: http://jsbin.com/midarozoze/1/edit?html,output

**Comment by arshad** [comment]
I'm trying to center it on Japan.

**Comment by arshad** [comment]
Japan has latitude 36° 00' N and longitude 138° 00' E. I'm trying to center it using a center as follows:

`d3.geo.mercator().center([36, 138]) // this does not work`

but swapping the values works.

`d3.geo.mercator().center([138, 36]) // this works`

**Comment by markmarkoh** [comment]
Center is always [long, lat]. Here are 2 examples of Japan vs Austin:

http://jsbin.com/huxitewuyu/1/edit?html,output

**Comment by arshad** [comment]
Hmm you're right. I was getting a false positive center using France's latitude and longitude. Confirmed: setting center using long, lat works. Thank You.

Any way I can help document this?

**Comment by markmarkoh** [comment]
@arshad Sure, if you wanted you could [update this example to use center](https://github.com/markmarkoh/datamaps#using-custom-maps) and specify the order of `long` and `lat`. Think that would have been useful?

**Comment by arshad** [comment]
PR #227

**Comment by arshad** [comment]
Thanks.
