### ISSUE TITLE
Add icons to a map

### ISSUE THREAD

**Issue by orf** [markmarkoh/datamaps#230]
Is it possible to add something akin to bubbles but with custom icons? I.e display a scaled mushroom cloud instead of a circular bubble, retaining the same options and functionality?

**Comment by markmarkoh** [comment]
I wrote up a plugin that does this, you can edit this code and change the image src for the new icon:
http://jsbin.com/uPOyuJU/1325/edit?html,output

Does that help?

**Comment by orf** [comment]
Awesome, this is perfect, thank you!
