### ISSUE TITLE
Create a new dist & npm release for all current merged changes

### ISSUE THREAD

**Issue by tmoitie** [markmarkoh/datamaps#232]
We are currently using a fork with the compiled changes we need to make work.

Thanks

**Comment by workgena** [comment]
I use rails-assets.org and they have datamaps 0.4.0 with broken dependencies on d3(for some reason). So I have to put datamaps.js in project-assets folder.

For me(and others rails users) would be good to have new release with updated dependencies.

**Comment by markmarkoh** [comment]
Updated with latest pull requests and some bugs.
