### ISSUE TITLE
make it easy to run the examples on the local machine

### ISSUE THREAD

**Issue by macmania** [markmarkoh/datamaps#236]
any one want to work on making it easy to run the example on their local machine so that devs can play around w/ the test code? 

it could just be as simple as ./run-examples.sh

**Comment by workgena** [comment]
I thought about that too. But, for me personnaly, it would be good to do:
1. $ git clone https://github.com/markmarkoh/datamaps.git
2. End simply drug&drop "example.html" in browser

Without any http-server or configuration. Additionally, would be grate to have some "index.html" with links and explanation to every example. I will think about this later this week.

**Comment by markmarkoh** [comment]
How about having links to JSBin's of examples, like: http://jsbin.com/nutawiboci/1/edit?html,output ?

I like it because you can alter and mess with the code directly without having to event check the project out.

**Comment by macmania** [comment]
I think that'll be better, maybe we can add in the examples README.md on how to run the samples using jsbin.
