### ISSUE TITLE
make border highlight thickness uniform around the perimeter

### ISSUE THREAD

**Issue by listx** [markmarkoh/datamaps#238]
If you go to http://datamaps.github.io/, the 3rd map down (USA map), and hover over California, the border is thicker on the coast than inland adjacent to the other states. This thinner border problem is prevalent in states like Colorado where the border is very thin, or Oklahoma where the top half's border highlight is thicker than the bottom.

This makes `highlightBorderWidth` not very correct --- some borders will respect the defined with, some will not.

**Comment by markmarkoh** [comment]
Fixed in 0.4.1
