### ISSUE TITLE
hideAntarctica: false appears to be ignored

### ISSUE THREAD

**Issue by DpadamsX** [markmarkoh/datamaps#254]
I've just found datamaps today and it's *fantastic*. So, thanks!

I'm planning to plot bird family distributions by country/region and could use Antartica for a couple of families but the hideAntarctica: false config directive seems to be ignored. I've tried it on my own page and here without ever seeing Antarctica show up:

http://jsbin.com/nerilagali/edit?html,js,output

**Comment by markmarkoh** [comment]
@DpadamsX I'm glad you like it!

One small gotchya, `hideAntarctica` needs to be set as a property of `geographyConfig`, so the right syntax would be like in this example:

http://jsbin.com/cegewiyumu/edit?html,js,output

**Comment by DpadamsX** [comment]
Thanks very much for the answer! The interactive map tester is great. I can see Antarctica there and can see how my geographyConfig settings are somehow breaking it too. I'll experiment now that I can move back and forth between working examples and my broken bits.

After that I'll move on to reading the various posts on how to center and scale automatically on smaller areas. When, for example, using a map of New Caledonia, New Zealand, or the like.

Thanks again!
