### ISSUE TITLE
Default configuration and options mismatch between website and GitHub

### ISSUE THREAD

**Issue by magic890** [markmarkoh/datamaps#266]
Default configuration and options [listed on the website](http://datamaps.github.io) are less than [these listed on GitHub project page](https://github.com/markmarkoh/datamaps/blob/master/README.md#default-options).

There is a way to community update the website (is it tracked on GitHub)?

**Comment by markmarkoh** [comment]
@magic890 A PR can be send here: https://github.com/datamaps/datamaps.github.com
