### ISSUE TITLE
map.labels({'customLabelText': newLabels}) is not working as expected

### ISSUE THREAD

**Issue by nikhileshcs** [markmarkoh/datamaps#270]
Only the default values are being displayed.

I've created the plnkr with the default example of custom-labels. It is not working yet.

Check this plnkr 

https://plnkr.co/edit/ManO6mgFreewTRnA32rY?p=preview

**Comment by markmarkoh** [comment]
@nikhileshcs Switch to `0.4.4` for that functionality:

```html
<script src="https://datamaps.github.io/scripts/0.4.4/datamaps.usa.min.js"></script>
```

**Comment by bigabdoul** [comment]
> @nikhileshcs Switch to `0.4.4` for that functionality:
> 
> ```
> <script src="https://datamaps.github.io/scripts/0.4.4/datamaps.usa.min.js"></script>
> ```

Does this mean that the labels method works only for the USA map? How about adding labels to any map?
