### ISSUE TITLE
Scaling causes some weird looking maps

### ISSUE THREAD

**Issue by lblinovs** [markmarkoh/datamaps#292]
So we use USA map with bubles and `responsive: true`. And on resize we call `map.resize()`.

If we initially render map on smaller screen:

![image](https://cloud.githubusercontent.com/assets/16575408/14888291/42abd0bc-0d62-11e6-85c9-99c327b9dc4a.png)

And then resize it:

![image](https://cloud.githubusercontent.com/assets/16575408/14888299/4c07c71a-0d62-11e6-87cc-7cb9252f9129.png)

Bubbles and borders become huge.

**Comment by lblinovs** [comment]
Created a workaround where I would change bubbles radius based on map `scale` value. And to fix border resizing I added a css property `vector-effect: non-scaling-stroke`

**Comment by markmarkoh** [comment]
@lblinovs that CSS property fix looks great, I think that should be added to the core project. Nice find.

**Comment by darkalor** [comment]
The css property deals with borders, but the bubbles are still oversized because of scale.
Why not just re-render the whole thing instead of using scale?

**Comment by markmarkoh** [comment]
Fixed with https://github.com/markmarkoh/datamaps/pull/301
