### ISSUE TITLE
3 state codes missing from datamaps.ind.js

### ISSUE THREAD

**Issue by gargsatish0** [markmarkoh/datamaps#297]
On line 780 in datamaps.ind.js, there are three ids that are missing the state codes and are represented as "IN.".
The corrections are as follows :
For "name" : "Tamil Nadu", "id" should be "IN.TN".
For "name" : "Gujarat", "id" should be "IN.GJ".
For "name" : "Daman and Diu", "id" should be "IN.DD".

Also, One of the state "Andhra Pradesh" is now divided into "Andra Pradesh" and "Telangana".
Can you give me some guidance on how can I achieve this.

Would appreciate any updates.

**Comment by magic890** [comment]
@markmarkoh ready to be closed after merge.
