### ISSUE TITLE
Zoom issue on arcs

### ISSUE THREAD

**Issue by magic890** [markmarkoh/datamaps#304]
Applying `vector-effect: non-scaling-stroke` to all `.path` include also arcs (https://github.com/markmarkoh/datamaps/pull/301/files#diff-ddbd8bd707d46180c6d87765093fe995R175).
(Black fill below the arc was added by me to highlight that arc extremities are placed correct while zooming).
This cause a weird behaviour on arcs using zoom:

![Vector Effect on Arc](https://cloud.githubusercontent.com/assets/1352670/15317269/0b4c03da-1c21-11e6-9105-cc7bb8dfae1f.gif)

**Comment by magic890** [comment]
@markmarkoh have you got any idea about why this happens?
I was guessing that maybe is due to curved line, but this strange behaviour does not apply on bubbles.

**Comment by Skinner927** [comment]
So, I don't know much about SVG, but try adding this CSS:

```
path.datamaps-arc {
  vector-effect: non-scaling-stroke; /* optional */
  stroke-dasharray: none !important;
  stroke-dashoffset: 1 !important;
}
```

**Comment by magic890** [comment]
@Skinner927 that was fixed by the merge, solved using `vector-effect: non-scaling-stroke;`. Thank you.
