### ISSUE TITLE
Bubbles not always displaying on map

### ISSUE THREAD

**Issue by corymcox** [markmarkoh/datamaps#317]
I find that refreshing the browser several times will often "fix" the issue... the code is as below:

[problem_code.txt](https://github.com/markmarkoh/datamaps/files/339701/problem_code.txt)

**Comment by markmarkoh** [comment]
Hi @corymcox 

I added your code to this JSFiddle and it seems to work fine: 
https://jsfiddle.net/y63qzv7p/

Do you see any console errors on your side?

**Comment by yusufozturk** [comment]
This issue still exist for v5

Open your JSFiddle in a new tab and wait for it to load, then go to that tab, you won't see any bubbles

**Comment by philipjnorton** [comment]
We are also having issues with bubbles not appearing on first load but after a few reloads they appear.

**Comment by markmarkoh** [comment]
@yusufozturk @philipjnorton 

I think it's a timing issue, wrapping the `map_us.bubbles()` inside the `done` function brings consistent results.

Can you verify this is working as expected?: https://jsfiddle.net/4rsp0t47/

**Comment by yusufozturk** [comment]
Hi Mark,

Still not working. You can test it by this:

1. Open your jsfiddle link in new tab.
2. Navigate that tab after page is loaded.
3. You won't see bubbles on that page.

I think bubbles also does not work in hidden divs like bootstrap tabs, or when there is a loading layer on page.

Yusuf

**Comment by yusufozturk** [comment]
Btw, this issue is not happening on Firefox, but happening on Chrome and Microsoft Edge.

Yusuf

**Comment by yusufozturk** [comment]
@philipjnorton setting animation: false for bubbles config seems like fixing this issue.

**Comment by philipjnorton** [comment]
Thanks for the reply @yusufozturk 
Where have you set this? within the bubblesConfig?

**Comment by yusufozturk** [comment]
@philipjnorton yes, it's like:

```
bubblesConfig: {
                    animate: false,
                    borderWidth: 2,
                    borderOpacity: 1,
                    borderColor: '#FFFFFF',
                    fillOpacity: 0.85
                },
```

so it's actually `animate: false`, not animation, sorry for that.

**Comment by sumeetattree** [comment]
I am facing the same issue. The maps tab is not the active one when the page loads for the first time. For me some bubbles load, others don't. No luck with `animate: false` either.
