### ISSUE TITLE
Complete full arc animation.

### ISSUE THREAD

**Issue by 0xnandhi** [markmarkoh/datamaps#322]
Hi, 

First of all thanks for awesome library.

I have something similar to this one.

```
data.forEach(function(val, index){
map.arc(....)
});
```
The above code gets called every half a second.

The arc animation is not getting completed, but, when it is in mid air, another map.arc call cancel's or clears all the map.arc animation. I tried d3.queue() and queued all arc data there. But even then it was not working. 

Is it possible to override this setting at a high level ?

Thanks

**Comment by markmarkoh** [comment]
@0xnandhi can you expand on the code a little bit more?

The problem is that `map.arc()` expects the full array of arcs, so the better approach would be to continuously add to an array of arcs.

So maybe something more like:
```javascript
var arcs = [];
data.forEach(function(val, index) {
  arcs.push(val);
  map.arcs(arcs);
});
```

**Comment by 0xnandhi** [comment]
Thanks for the info. Let me try to reproduce it and see if this works.
