### ISSUE TITLE
disable popup/hover for certain regions

### ISSUE THREAD

**Issue by ashishtyagi109** [markmarkoh/datamaps#324]
Currently popup/hover can either be enabled for the entire map or not at all. Many use cases do not require every country/state on the map though, so being able to disable popup/hover on these regions would be a very useful feature to have.

**Comment by markmarkoh** [comment]
@ashishtyagi109 You can override `popupTemplate` to return nothing, like:

```
...,
popupTemplate: function(geo, data) {
  if (!data) return;
  return '<div>' + data.somedata + '</div>'
},
```

Working example, only the USA should have a popover:
https://jsfiddle.net/j8w4bL7t/
