### ISSUE TITLE
Populate arcs from data

### ISSUE THREAD

**Issue by lynnco** [markmarkoh/datamaps#342]
As far as I can tell, the only thing I can do with the json I pass to `Datamaps.dataUrl` is give a particular country a color. How would I use that data to populate arcs?

**Comment by markmarkoh** [comment]
@lynnco I think your best bet for populating arcs from an AJAX request is to fetch the data using `d3.json` manually.

For instance:

```javascript
var map = new Datamap({
  scope: 'world',
  done: function() { 
    // fetch JSON for arcs
    d3.json('/my-arcs-data.json', function(err, data) {
      map.arcs(data)
    })
  })
})
```
