### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.geo[b.projection]')

### ISSUE THREAD

**Issue by Caroldm** [markmarkoh/datamaps#359]
Hi,

I tried using datamaps. But I'm getting the error:
TypeError: undefined is not an object (evaluating 'n.geo[b.projection]')
Any ideas why this is happening?

Thank you

**Comment by andresteves** [comment]
Would love to know what is causing this error. Anyone?

**Comment by ypicard** [comment]
I have the same problem, any news ?

**Comment by ypicard** [comment]
Switching from d3v4 to d3v3 worked for me, thanks to this [post](https://stackoverflow.com/questions/42846588/uncaught-typeerror-cannot-read-property-albersusa-of-undefined)
