### ISSUE TITLE
Full example of custom maps

### ISSUE THREAD

**Issue by raubreywhite** [markmarkoh/datamaps#36]
Hi,

I'm really struggling to follow your custom maps documentation. If you could include a fully working example of a custom map, that would be amazing.

Thanks

**Comment by DanDvoracek** [comment]
What is the uk map in this directory? 
https://github.com/markmarkoh/datamaps/tree/master/dist

I tried all the combinations (UK, GB, GBR,...) and none of them have shown UK only when using the datamap.all.min.js.. Any idea? (Referring to your USA only example...)

Thanks,
