### ISSUE TITLE
how to add a new country (singapore) attributes in the map?

### ISSUE THREAD

**Issue by turbowars** [markmarkoh/datamaps#43]
Hi,

I know for a fact that I have to modify the world.js file to add new countries.
I am unable to figure out what the "arcs" attributes do? how to set attributes for a new country like singapore?

{
                    "type": "Polygon",
                        "id": "AFG",
                        "arcs": [
                        [0, 1, 2, 3, 4, 5]
                    ],
                        "properties": {
                        "name": "Afghanistan"
                    }
                }

**Comment by jonathanstowell** [comment]
Did you manage to be able to add the additional missing countries in the end? If so would you be able to share the arcs for those countries?

**Comment by zzoi** [comment]
The link is broken for the custom map data with datamaps. I have the same issue.
Any help adding singapore to the map?

**Comment by zzoi** [comment]
I found a map with additional countries and created a custom Datamap with a TopoJSON file and it works.
Following the instructions from here: http://bl.ocks.org/markmarkoh/8717334

Here is my solution. 
https://gist.github.com/zzoi/97b68cb3a09a7f04a8ac
