### ISSUE TITLE
Help with D3.js maps

### ISSUE THREAD

**Issue by mcangial0821** [markmarkoh/datamaps#44]
I am new to the D3 mapping. I am trying to figure out how to set up a map for New York State and then show data either by county of congressional district.

**Comment by mg1075** [comment]
For USA county-level maps by state (not a map of the entire USA), is there by now an easy resource for files, with MIT license, for each state? Or when people need these maps, do they always have to make them on their own? (And apparently this process of making topojson files is not so straightforward for a Windows user?)
