### ISSUE TITLE
v0.5.9 not published to npm

### ISSUE THREAD

**Issue by mike-packetwerk** [markmarkoh/datamaps#444]
Hi,

It seems that v0.5.9 has not been published to npm. https://www.npmjs.com/package/datamaps is still showing v0.5.8 as the latest.

**Comment by markmarkoh** [comment]
@mike-packetwerk I've updated and deployed the latest (0.5.9)

![ex](https://cl.ly/3C022M1a3k1W/Screen%20Shot%202018-05-14%20at%206.29.50%20PM.png)

**Comment by mike-packetwerk** [comment]
Great, thanks!
