### ISSUE TITLE
Responsive Maps and Continuous Legends

### ISSUE THREAD

**Issue by ramnathv** [markmarkoh/datamaps#45]
I am digging datamaps and find it to be the perfect solution to quickly generate choropleths and bubble maps.  I came across this [post](http://eyeseast.github.io/visible-data/2013/08/27/responsive-legends-with-d3/) on responsive maps with d3.js. Is it possible to adapt some of the ideas from this post to make the maps made with datamaps responsive?

**Comment by hoprocker** [comment]
Has this been resolved?
