### ISSUE TITLE
Custom JSON & Orthographic Projection

### ISSUE THREAD

**Issue by Wiljanneman** [markmarkoh/datamaps#482]
Hi 

This is one of my first attempts building a map with Custom JSON and I seem to be having trouble getting the orthographic projection right.

So I'm using a custom topojson (converted a .shp file) I got from a [thinkquest archive](http://web.archive.org/web/20080328104539/http://library.thinkquest.org:80/C006628/download.html). It's the 1880 one.

![orto](https://user-images.githubusercontent.com/17082974/51805196-280c7800-2273-11e9-80be-0e10c5900fae.PNG)

It doesn't look too bad, but as indicated in the image, certain continents/island seem to show when they're in fact located on the other side of the globe.  

I'm wondering is it a styling issue in particular or perhaps a projection issue?  Advice would be greatly appreciated.  I can manually show/hide according to the current rotation, but I'm wondering if there aren't any simpler fixes.

Here's a code snippet:

```
<!DOCTYPE html>
<meta charset="utf-8">
<body>
  <script src="http://d3js.org/d3.v3.min.js"></script>
  <script src="http://d3js.org/topojson.v1.min.js"></script>
  <script src="http://rawgithub.com/markmarkoh/datamaps/master/dist/datamaps.none.min.js"></script>
  <h2>Datamaps</h2>
  <div id="container1" style="position: relative; width: 5000px; height: 500px;"></div>
 
     <script>
       var globalMapZA;
var globalMapWorld;
var globalRotation = [90, -30];
var globalScale = 500;
var globalCenter = [53 * -1, -2 * -1];
var redrawData;
var globalProjection;

      var map = new Datamap({
        scope: 'collection',
        element: document.getElementById('container1'),
        responsive: true,
        fills: {
          defaultFill: 'rgba(0,0,0,0.7)',
          lt50: 'rgba(0,244,244,0.9)',
          gt50: 'red'
        },
        geographyConfig: {
            dataUrl: '/js/map.topojson'
        },
        setProjection: function (element) {
            var projection = d3.geo.orthographic()
                .scale(globalScale)
                .translate([element.clientWidth / 2, element.clientHeight / 2]);
            var path = d3.geo.path()
                .projection(projection);

            return { path: path, projection: projection };
        }
      });
      map.graticule();
      
     </script>
</body>
```

Thanks in advance,
Will

**Comment by markmarkoh** [comment]
Hi @Wiljanneman,

The code inside datamaps that presents an othrographic projection looks like this:

```js
    if ( options.projection === 'orthographic' ) {

      svg.append("defs").append("path")
        .datum({type: "Sphere"})
        .attr("id", "sphere")
        .attr("d", path);

      svg.append("use")
          .attr("class", "stroke")
          .attr("xlink:href", "#sphere");

      svg.append("use")
          .attr("class", "fill")
          .attr("xlink:href", "#sphere");
      projection.scale(250).clipAngle(90).rotate(options.projectionConfig.rotation)
    }
```

So perhaps an option there, like `cilpAngle` or the `defs/use` might fix the issue for you?

**Comment by Wiljanneman** [comment]
> Hi @Wiljanneman,
> 
> The code inside datamaps that presents an othrographic projection looks like this:
> 
> ```js
>     if ( options.projection === 'orthographic' ) {
> 
>       svg.append("defs").append("path")
>         .datum({type: "Sphere"})
>         .attr("id", "sphere")
>         .attr("d", path);
> 
>       svg.append("use")
>           .attr("class", "stroke")
>           .attr("xlink:href", "#sphere");
> 
>       svg.append("use")
>           .attr("class", "fill")
>           .attr("xlink:href", "#sphere");
>       projection.scale(250).clipAngle(90).rotate(options.projectionConfig.rotation)
>     }
> ```
> 
> So perhaps an option there, like `cilpAngle` or the `defs/use` might fix the issue for you?

Presto!  I added the code with my own rotation and scale and it's working fine.

![orto-correct](https://user-images.githubusercontent.com/17082974/51848653-a70eb880-2326-11e9-97c5-d8a657ad0af0.PNG)

Thanks @markmarkoh
