### ISSUE TITLE
Issues loading dependencies with RequireJS

### ISSUE THREAD

**Issue by perks** [markmarkoh/datamaps#49]
Hey, I noticed that when trying to include datamaps in some sort of AMD pattern, there is an error triggered that I can't seem to figure out

Here is a picture of the network requests showing that all libraries are loading in the intended order: 

![screen shot 2014-02-04 at 4 42 19 pm](https://f.cloud.github.com/assets/1820298/2081675/c900766c-8de5-11e3-97fc-c3e915b8a9a8.png)

And here is my RequireJS settings:

app.js:

```
requirejs.config({
  'baseUrl': 'js/lib',
  'paths': {
    'app': '../app',
    'jquery': 'jquery',
    'd3': 'd3',
    'topojson': 'topojson',
    'domReady': 'domReady',
    'datamaps': 'datamaps'
  },
  shim: {
    d3: {
      exports: 'd3'
    },
    topojson: {
      deps: ['d3'],
      exports: 'topojson'
    },
    datamaps: {
      deps: ['d3', 'topojson']
    }
  }

});

/** Load main module to start app **/
requirejs(["app/main"]);


```

And here is the main app that is being run:

main.js:

```
define(function(require) {
  var $ = require('jquery');
  var d3 = require('d3');
  var topojson = require('topojson');
  var domReady = require('domReady');
  var Datamap = require('datamaps');

  domReady(function() {
    // Begin drawing for SVG map
   var map = new Datamap({element: $('#container')[0]});
    });

});
```

And here is the HTML:

```
<html>
  <head>
    <script data-main="js/app" src="js/lib/require.js"></script>
  </head>
  <body>
    <h1>Testing</h1>
    <p>Testing the page</p>
    <div id="container" style="position: relative; width: 500px; height: 300px;"></div>
  </body>
</html>
```

Every time it runs though I get the error:

```
Uncaught Error: Include d3.js (v3.0.3 or greater) and topojson on this page before creating a new map 
```

This is what happens when I add the lines:

```
console.log(d3);
console.log(topojson);
```

to main.js:

```
define(function(require) {
  var $ = require('jquery');
  var d3 = require('d3');
  var topojson = require('topojson');
  var domReady = require('domReady');
  var Datamap = require('datamaps');

  domReady(function() {
    // Begin drawing for SVG map
   console.log(d3);
   console.log(topojson);
   var map = new Datamap();
    });

});
```

which gives the result as follows:
![screen shot 2014-02-04 at 4 52 59 pm](https://f.cloud.github.com/assets/1820298/2081760/ce3a6a38-8de6-11e3-9c41-73c3f5086967.png)

Any ideas of what could be going wrong?

both d3 and topojson are clearly being loaded, been having a heart attack trying to work this out haha

**Comment by WunderBart** [comment]
I'm having the same issue, @bitoiu. It happens with minimized versions only though. Right now as a workaround I require `d3` globally and it works fine. Any ideas how to make it work properly, @markmarkoh?

**Comment by liorwohl** [comment]
hi, 
I'm trying to integrate datamaps into my project which use Browserify with NPM.
there two problems:
require('datamaps'); 
wont work because your package.json file dont have "main" attribute, so adding:
"main": "dist/datamaps.all.js",
to datamaps/package.json fix it (but its a temp fix until you commit it)

the other problem which I cant figure how to fix is the same problem as in this bug, when doing:
var d3 = require('d3');
require('topojson');
require('datamaps');
I get the error: "Include d3.js (v3.0.3 or greater) and topojson on this page before creating a new map"
In the console watch i see that d3 is there, but topojson is undefined. 
what can I do?

thanks

**Comment by liorwohl** [comment]
i found a quick ugly fix - adding 
<script src="http://cdnjs.cloudflare.com/ajax/libs/topojson/1.6.19/topojson.min.js"></script>
in the head tag fix the problem.
but i would really like to use require()...

**Comment by timaschew** [comment]
Please reopen this issue, it's not fixed yet.

I'm using latest versions of these modules, installed via npm and I still get the error 

__Uncaught Error: Include d3.js (v3.0.3 or greater) and topojson on this page before creating a new map__

```
├── d3@3.5.16
├─┬ datamaps@0.4.4
│ └── d3@3.5.16
└─┬ topojson@1.6.24
  └── d3@3.5.16
```

**Comment by markmarkoh** [comment]
Can you share the source of how you are loading up DataMaps? `<script>` tags, `require()`, `import`, etc.

**Comment by Ushanta** [comment]
![Uploading image.png…]()

Hi Mark

Can you help me with this issue:

I am using datamaps in conjunction with requirejs. I get an 'undefined' object when injecting the datamaps.world.min.js. I have also tried https://raw.githubusercontent.com/markmarkoh/datamaps/amd-issues/dist/datamaps.all.js.


If you look at the screenshot the other objects (topojson, d3, elasticsearch) are all found.
