### ISSUE TITLE
Slight redesign of Legend possible? 

### ISSUE THREAD

**Issue by xammamax** [markmarkoh/datamaps#50]
Now the legend is displayed like this: 1-12 ▒ 13-450 ▓

Would it be possible to have this: 
 1-12 ┈ 13-450 
  ┈ ▒ ┈┈ ▓
so that the color boxes and the labels are in two rows rather than in one?

An issue with the current design is that if you limit the width in which the legend is shown (to display the legend vertically instead of horizontally) you end up with something like this:
1-12 ▒ 
13-450 ▓
the color boxes are not aligned horizontally.

(A quick fix might be to swap the color boxed and the text label. i.e.:   ▒ 1-12 ▓ 13-450 . That way the color boxes are always vertically aligned if you limit the width like before.
It would be:
▒ 1-12
▓ 13-450 ) 

Thank you for the great datamaps!

**Comment by spdaly** [comment]
THANKS!

**Comment by madrien** [comment]
This worked. However, when I add the custom labels the legend is blank. Is there something additional needed?

  //Show Legend 
   map_locations.addPlugin("mylegend", addLegendmaxstyle);
   map_locations.mylegend({
       legendTitle:"Legend",
        labels: {
          yellow: "Campuses",
          blue: "Centers",
          darkGray: "All"
        },
       
   })

Without this plugin the custom label names show with no issue.
