### ISSUE TITLE
How to pass custom legend labels?

### ISSUE THREAD

**Issue by matt-bernhardt** [markmarkoh/datamaps#63]
I'm looking over the source code for the legend, and am trying to understand how custom label text should be specified. I've been able to set the legend title, and the default label, using
```
map.legend({
    legendTitle : "Total Downloads",
    defaultFillName: "No data",
})
```

However, the example that ronaldbradford gives in #39 isn't working? Here is how I'm calling the map
```
  var map = new Datamap({
    element: document.getElementById('map'),
    geographyConfig: {
      popupTemplate: function(geography, data) {
        return '<div class="hoverinfo"><strong>' + geography.properties.name + '<br>' + data.downloads.toLocaleString() + '</strong></div>';
      }
    },
    fills: {
      defaultFill: "#cccccc",
      q0: "rgb(242,242,242)",
      q1: "rgb(173,186,206)",
      q2: "rgb(132,152,181)",
      q3: "rgb(90,117,156)",
      q4: "rgb(49,83,132)",
      q5: "rgb(8,48,107)",
    },
    data: mapdata
  });

  map.legend({
    legendTitle : "Total Downloads",
    defaultFillName: "No data",
    labels: {
      q0: "one",
      q1: "two",
      q2: "three",
      q3: "four",
      q4: "five",
      q5: "six,"
    },
  });
```

Any pointers would be appreciated -

**Comment by nsasto** [comment]
there's a syntax error in your code - remove the last trailing comma and you should be good. So 
 q3: "four",
      q4: "five",
      q5: "six,"
    },
  });

should be 
 q3: "four",
      q4: "five",
      q5: "six,"
    }
  });
