### ISSUE TITLE
Support for "3d" globe

### ISSUE THREAD

**Issue by rayshan** [markmarkoh/datamaps#77]
Thanks for all your hard work Mark. It would be awesome if we can have support for a "3d" globe, such as:
http://bl.ocks.org/mbostock/6619561
http://bl.ocks.org/syntagmatic/6645345
http://bl.ocks.org/mbostock/4183330

Perhaps it's already easily configurable out of the box, and just needed an example in the docs?

**Comment by davorb** [comment]
It's already in there.

```js
new Datamap({ projection: 'orthographic' });
```
