### ISSUE TITLE
Support specifying color value without using fillKey upon map instantiation

### ISSUE THREAD

**Issue by rayshan** [markmarkoh/datamaps#78]
Hello, there doesn't seem to be a way to specify color without using `fillKey` or calling `updateChoropleth` after map is instantiated. Below do not seem to work with color name or hex value:

``` javascript
data: {
  USA: 'white'
}
```

``` javascript
data: {
  USA: {fill: 'white'}
}
```

``` javascript
fills: {
  USA: 'white'
}
```

**Comment by hoprocker** [comment]
+1. The `fillKey` method is kind of limiting; what if you want to use a function to generate the color based on the data that gets returned (i.e. with the [threshold choropleth](http://bl.ocks.org/mbostock/3306362) example)? I.e, 

```javascript
var fillColor = d3.scale.threshold().domain([.05, .10]).range(['#333333', '#888888']);

map.updateChoropleth({
    USA: {fill: fillColor(data['USA'])}
})
```

...or something like that. Here, when I update the data, I don't want to choose between updating all of the data (which I may also want to use in a hover dialog) or just the color.

I'm going to try and think up an elegant solution that allows for this and also accommodates the legacy syntax.

**Comment by markmarkoh** [comment]
@hoprocker This was added in the latest version, (under the `fillColor` key).

Example:
http://jsbin.com/vibucobono/1/edit

**Comment by markmarkoh** [comment]
@hoprocker Let me know if you have any questions!

**Comment by hoprocker** [comment]
Oh wow, there it is in bold at the top of the release notes. I'll submit a PR to update the main README.

Btw, thanks for the great library!
