### ISSUE TITLE
Error when changed scope

### ISSUE THREAD

**Issue by Solidary** [markmarkoh/datamaps#79]
Hi, 

I am a guy with D3.js and DataMaps.

I would like to display just for Cameroon country. So after including datamaps.all.min.js the rest of my code is
var map = new Datamap({
                scope : 'cmr',
                element : document.getElementById('container'),
            });

I have this error Uncaught TypeError: Cannot read property 'objects' of undefined. Even when I changed scope by other country.

Any solutions please ?
Thanks.

**Comment by EdisonDevadoss** [comment]
HI,
Can anybody help me to zoom in to India?
