### ISSUE TITLE
US with PR and VI

### ISSUE THREAD

**Issue by designsbybrandon** [markmarkoh/datamaps#9]
I'm trying to map a companies locations and was wondering if it is it possible to have a US map that also displays Puerto Rico and the US Virgin Islands? I thought this might be the listing on the main page saying a build is available for "USA & Countries w/ dependencies" but I see no documentation on how to access this.

**Comment by zzweber** [comment]
Hi designbybrandon,

Where did you add continent:"USA" in datamaps-all.js?
